interface IProduct {
    id: number;
    image: string;
    category: string;
    name: string;
    price: string;
    stars: number;
    reviews: string[];
}

interface IProductDeals {
    id: number;
    image: string;
    category: string;
    name: string;
    price: string;
    old_price: string;
    stars: number;
    reviews: string[];
}

interface IAllProducts {
    household: IProduct[];
    computers: IProduct[];
    phones: IProduct[];
    gaming: IProduct[];
    watches: IProduct[];
}

export const Products: IAllProducts = {
    household: [
        {
            id: 0,
            image: "https://res.cloudinary.com/dj25aashz/image/upload/v1689472625/e-gadgets/household_01_naw2ye.jpg",
            category: "Household",
            name: "Hisense 7.5kg Hisense Top Loader Manual Washing Machine (WSQB753)",
            price: "₦ 95,000",
            stars: 3,
            reviews: [
                "Sed egestas, ante et vulputate volutpat, eros pede",
                "Semper est, vitae luctus metus libero eu augue. Morbi purus libero, faucibus adipiscing. Sed lectus.",
            ],
        },

        {
            id: 1,
            image: "https://res.cloudinary.com/dj25aashz/image/upload/v1689472625/e-gadgets/household_02_d764gi.jpg",
            category: "Household",
            name: "7KG 1000W Electric Clothes Dryer Wardrobe Energy Save",
            price: "₦ 55,000",
            stars: 4,
            reviews: [
                "Sed egestas, ante et vulputate volutpat, eros pede",
                "Semper est, vitae luctus metus libero eu augue. Morbi purus libero, faucibus adipiscing. Sed lectus.",
            ],
        },

        {
            id: 2,
            image: "https://res.cloudinary.com/dj25aashz/image/upload/v1689472626/e-gadgets/household_03_hopoyl.jpg",
            category: "Household",
            name: "Nexus 45 Litres Bedside Refrigerator (NX-65) - Silver",
            price: "₦ 58,690",
            stars: 2,
            reviews: [
                "Sed egestas, ante et vulputate volutpat, eros pede",
                "Semper est, vitae luctus metus libero eu augue. Morbi purus libero, faucibus adipiscing. Sed lectus.",
            ],
        },
        {
            id: 3,
            image: "https://res.cloudinary.com/dj25aashz/image/upload/v1689472626/e-gadgets/household_04_bbrdnm.jpg",
            category: "Household",
            name: "Hisense 1HP Split Copper Inverter Air Conditioner (AS09DK)",
            price: "₦ 197,900",
            stars: 1,
            reviews: [
                "Sed egestas, ante et vulputate volutpat, eros pede",
                "Semper est, vitae luctus metus libero eu augue. Morbi purus libero, faucibus adipiscing. Sed lectus.",
            ],
        },
        {
            id: 4,
            image: "https://res.cloudinary.com/dj25aashz/image/upload/v1689472626/e-gadgets/household_05_mabscw.jpg",
            category: "Household",
            name: "Midea 10kgTwin Tub Washing Machine",
            price: "₦ 197,90",
            stars: 2,
            reviews: [
                "Sed egestas, ante et vulputate volutpat, eros pede",
                "Semper est, vitae luctus metus libero eu augue. Morbi purus libero, faucibus adipiscing. Sed lectus.",
            ],
        },
        {
            id: 5,
            image: "https://res.cloudinary.com/dj25aashz/image/upload/v1689472625/e-gadgets/household_06_fembuz.jpg",
            category: "Household",
            name: "Haier Thermocool 319 Litres Medium Chest Freezer (HTF-319IW)",
            price: "₦ 264,000",
            stars: 4,
            reviews: [
                "Sed egestas, ante et vulputate volutpat, eros pede",
                "Semper est, vitae luctus metus libero eu augue. Morbi purus libero, faucibus adipiscing. Sed lectus.",
            ],
        },
        {
            id: 6,
            image: "https://res.cloudinary.com/dj25aashz/image/upload/v1689472626/e-gadgets/household_07_sifyfq.jpg",
            category: "Household",
            name: "Hisense 20 Litres (H20MOWS10) Microwave",
            price: "₦ 38,940",
            stars: 4,
            reviews: [
                "Sed egestas, ante et vulputate volutpat, eros pede",
                "Semper est, vitae luctus metus libero eu augue. Morbi purus libero, faucibus adipiscing. Sed lectus.",
            ],
        },
        {
            id: 7,
            image: "https://res.cloudinary.com/dj25aashz/image/upload/v1689472627/e-gadgets/household_08_vsm1m7.jpg",
            category: "Household",
            name: "Hisense 8KG Anti-Crease Tumble Dryer- Lagos Delivery Only",
            price: "₦ 184,400",
            stars: 4,
            reviews: [
                "Sed egestas, ante et vulputate volutpat, eros pede",
                "Semper est, vitae luctus metus libero eu augue. Morbi purus libero, faucibus adipiscing. Sed lectus.",
            ],
        },
        {
            id: 8,
            image: "https://res.cloudinary.com/dj25aashz/image/upload/v1689472626/e-gadgets/household_09_y8shyp.jpg",
            category: "Household",
            name: "Silver Crest 2 Litres German Industrial Blender With Mill Jar",
            price: "₦ 16,800",
            stars: 2,
            reviews: [
                "Sed egestas, ante et vulputate volutpat, eros pede",
                "Semper est, vitae luctus metus libero eu augue. Morbi purus libero, faucibus adipiscing. Sed lectus.",
            ],
        },
        {
            id: 9,
            image: "https://res.cloudinary.com/dj25aashz/image/upload/v1689472627/e-gadgets/household_10_g4zauu.jpg",
            category: "Household",
            name: "Bear 3.6L Air Fryer Multi-functional Oil Free QZG-A14M1",
            price: "₦ 18,414",
            stars: 3,
            reviews: [
                "Sed egestas, ante et vulputate volutpat, eros pede",
                "Semper est, vitae luctus metus libero eu augue. Morbi purus libero, faucibus adipiscing. Sed lectus.",
            ],
        },
        {
            id: 10,
            image: "https://res.cloudinary.com/dj25aashz/image/upload/v1689472627/e-gadgets/household_11_xjixve.jpg",
            category: "Household",
            name: "Pyramid 22Litres(LARGE) Electric Oven,Baking,Toasting,Grilling",
            price: "₦ 27,700",
            stars: 5,
            reviews: [
                "Sed egestas, ante et vulputate volutpat, eros pede",
                "Semper est, vitae luctus metus libero eu augue. Morbi purus libero, faucibus adipiscing. Sed lectus.",
            ],
        },
        {
            id: 11,
            image: "https://res.cloudinary.com/dj25aashz/image/upload/v1689472627/e-gadgets/household_12_lz87xn.jpg",
            category: "Household",
            name: "Speed Electric Hand Mixer",
            price: "₦ 4,980",
            stars: 2,
            reviews: [
                "Sed egestas, ante et vulputate volutpat, eros pede",
                "Semper est, vitae luctus metus libero eu augue. Morbi purus libero, faucibus adipiscing. Sed lectus.",
            ],
        },
        {
            id: 12,
            image: "https://res.cloudinary.com/dj25aashz/image/upload/v1689472627/e-gadgets/household_13_nq6rma.jpg",
            category: "Household",
            name: "3 In 1 Waffle-Sandwich And Grill Maker",
            price: "₦ 19,699",
            stars: 4,
            reviews: [
                "Sed egestas, ante et vulputate volutpat, eros pede",
                "Semper est, vitae luctus metus libero eu augue. Morbi purus libero, faucibus adipiscing. Sed lectus.",
            ],
        },
        {
            id: 13,
            image: "https://res.cloudinary.com/dj25aashz/image/upload/v1689472597/e-gadgets/household_14_ghjhpm.jpg",
            category: "Household",
            name: "Savanna Juice Extractor - STAINLESS",
            price: "₦ 19,000",
            stars: 4,
            reviews: [
                "Sed egestas, ante et vulputate volutpat, eros pede",
                "Semper est, vitae luctus metus libero eu augue. Morbi purus libero, faucibus adipiscing. Sed lectus.",
            ],
        },
        {
            id: 14,
            image: "https://res.cloudinary.com/dj25aashz/image/upload/v1689472627/e-gadgets/household_15_qhgjmj.jpg",
            category: "Household",
            name: "Ox PLUS 18 Standing Fan",
            price: "₦ 12,790",
            stars: 3,
            reviews: [
                "Sed egestas, ante et vulputate volutpat, eros pede",
                "Semper est, vitae luctus metus libero eu augue. Morbi purus libero, faucibus adipiscing. Sed lectus.",
            ],
        },
        {
            id: 15,
            image: "https://res.cloudinary.com/dj25aashz/image/upload/v1689472627/e-gadgets/household_16_ayls6y.jpg",
            category: "Household",
            name: "Wireless Automatic Electric Gallon Bottled Rechargeable Water Pump Dispenser",
            price: "₦ 4,500",
            stars: 2,
            reviews: [
                "Sed egestas, ante et vulputate volutpat, eros pede",
                "Semper est, vitae luctus metus libero eu augue. Morbi purus libero, faucibus adipiscing. Sed lectus.",
            ],
        },
        {
            id: 16,
            image: "https://res.cloudinary.com/dj25aashz/image/upload/v1689472628/e-gadgets/household_17_jsflmf.jpg",
            category: "Household",
            name: "Ugasun Electric Slow Juicer With Large Feeder",
            price: "₦ 68,999",
            stars: 5,
            reviews: [
                "Sed egestas, ante et vulputate volutpat, eros pede",
                "Semper est, vitae luctus metus libero eu augue. Morbi purus libero, faucibus adipiscing. Sed lectus.",
            ],
        },
        {
            id: 17,
            image: "https://res.cloudinary.com/dj25aashz/image/upload/v1689472628/e-gadgets/household_18_udy7bl.jpg",
            category: "Household",
            name: "GDTIMES 12 Inches Rechargeable Table Fan With DC Bulbs+ Solar Panel",
            price: "₦ 24,900",
            stars: 5,
            reviews: [
                "Sed egestas, ante et vulputate volutpat, eros pede",
                "Semper est, vitae luctus metus libero eu augue. Morbi purus libero, faucibus adipiscing. Sed lectus.",
            ],
        },

        {
            id: 18,
            image: "https://res.cloudinary.com/dj25aashz/image/upload/v1689472634/e-gadgets/household_19_v6c9px.jpg",
            category: "Household",
            name: "Double Face Shoe Rack + Fabric Cover For 36 Pairs",
            price: "₦ 13,350",
            stars: 4,
            reviews: [
                "Sed egestas, ante et vulputate volutpat, eros pede",
                "Semper est, vitae luctus metus libero eu augue. Morbi purus libero, faucibus adipiscing. Sed lectus.",
            ],
        },
        {
            id: 19,
            image: "https://res.cloudinary.com/dj25aashz/image/upload/v1689472637/e-gadgets/household_20_dhiqn6.jpg",
            category: "Household",
            name: "260mL Mist Humidifier Diffuser Colorful Night Light Quiet",
            price: "₦ 3,200",
            stars: 5,
            reviews: [
                "Sed egestas, ante et vulputate volutpat, eros pede",
                "Semper est, vitae luctus metus libero eu augue. Morbi purus libero, faucibus adipiscing. Sed lectus.",
            ],
        },
    ],
    computers: [
        {
            id: 0,
            image: "https://res.cloudinary.com/dj25aashz/image/upload/v1689472634/e-gadgets/laptop_01_ijtw4y.jpg",
            category: "Computers",
            name: "Hp Notebook 14 Intel Celeron N4020 8GB RAM 1TB HDD Windows 10 + HP Mouse & USB Light",
            price: "₦ 182,000",
            stars: 4,
            reviews: [
                "Sed egestas, ante et vulputate volutpat, eros pede",
                "Semper est, vitae luctus metus libero eu augue. Morbi purus libero, faucibus adipiscing. Sed lectus.",
            ],
        },
        {
            id: 1,
            image: "https://res.cloudinary.com/dj25aashz/image/upload/v1689472634/e-gadgets/laptop_02_yootb9.jpg",
            category: "Computers",
            name: "Apple MacBook Pro 14 M1 Pro Chip 16GB RAM, 512GB (2021 Model)",
            price: "₦ 1,372,650",
            stars: 2,
            reviews: [
                "Sed egestas, ante et vulputate volutpat, eros pede",
                "Semper est, vitae luctus metus libero eu augue. Morbi purus libero, faucibus adipiscing. Sed lectus.",
            ],
        },
        {
            id: 2,
            image: "https://res.cloudinary.com/dj25aashz/image/upload/v1689472634/e-gadgets/laptop_03_xccyc9.jpg",
            category: "Computers",
            name: "Hp 15 Intel Celeron N4020 8GB RAM/1TB HDD Win 10 +Keyboard",
            price: "₦ 189,500",
            stars: 3,
            reviews: [
                "Sed egestas, ante et vulputate volutpat, eros pede",
                "Semper est, vitae luctus metus libero eu augue. Morbi purus libero, faucibus adipiscing. Sed lectus.",
            ],
        },
        {
            id: 3,
            image: "https://res.cloudinary.com/dj25aashz/image/upload/v1689472638/e-gadgets/laptop_04_ghqbdr.jpg",
            category: "Computers",
            name: "Hp 255 G8 AMD ATHLON 3150U 1TB HDD 8GB 15.6",
            price: "₦ 172,000",
            stars: 4,
            reviews: [
                "Sed egestas, ante et vulputate volutpat, eros pede",
                "Semper est, vitae luctus metus libero eu augue. Morbi purus libero, faucibus adipiscing. Sed lectus.",
            ],
        },
        {
            id: 4,
            image: "https://res.cloudinary.com/dj25aashz/image/upload/v1689472637/e-gadgets/laptop_05_ncqus2.jpg",
            category: "Computers",
            name: "Apple 13.6 MacBook Air (M2, Midnight) 8GB /256gb",
            price: "₦ 950,000",
            stars: 1,
            reviews: [
                "Sed egestas, ante et vulputate volutpat, eros pede",
                "Semper est, vitae luctus metus libero eu augue. Morbi purus libero, faucibus adipiscing. Sed lectus.",
            ],
        },
        {
            id: 5,
            image: "https://res.cloudinary.com/dj25aashz/image/upload/v1689472637/e-gadgets/laptop_06_ns2bot.jpg",
            category: "Computers",
            name: "DELL Latitude 3350 Intel Pentium 8GB RAM, 256GB SSD",
            price: "₦ 140,000",
            stars: 2,
            reviews: [
                "Sed egestas, ante et vulputate volutpat, eros pede",
                "Semper est, vitae luctus metus libero eu augue. Morbi purus libero, faucibus adipiscing. Sed lectus.",
            ],
        },
        {
            id: 6,
            image: "https://res.cloudinary.com/dj25aashz/image/upload/v1689472639/e-gadgets/laptop_07_oa6mh6.jpg",
            category: "Computers",
            name: "Lenovo V15-IGL - Celeron N4020 4GB 256GB - FreeDOS",
            price: "₦ 129,800",
            stars: 3,
            reviews: [
                "Sed egestas, ante et vulputate volutpat, eros pede",
                "Semper est, vitae luctus metus libero eu augue. Morbi purus libero, faucibus adipiscing. Sed lectus.",
            ],
        },
        {
            id: 7,
            image: "https://res.cloudinary.com/dj25aashz/image/upload/v1689472639/e-gadgets/laptop_08_gfvwql.jpg",
            category: "Computers",
            name: "Acer Spin 3 X360 Core I5,8gb,256 SSD,Backlit Keyboard Wins 10",
            price: "₦ 439,950",
            stars: 4,
            reviews: [
                "Sed egestas, ante et vulputate volutpat, eros pede",
                "Semper est, vitae luctus metus libero eu augue. Morbi purus libero, faucibus adipiscing. Sed lectus.",
            ],
        },
        {
            id: 8,
            image: "https://res.cloudinary.com/dj25aashz/image/upload/v1689472639/e-gadgets/laptop_09_erjw0s.jpg",
            category: "Computers",
            name: "DELL XPS 13 9315 Core I7-1250U 1TB SSD 32GB DDR5 RAM 13.4",
            price: "₦ 1,320,000",
            stars: 5,
            reviews: [
                "Sed egestas, ante et vulputate volutpat, eros pede",
                "Semper est, vitae luctus metus libero eu augue. Morbi purus libero, faucibus adipiscing. Sed lectus.",
            ],
        },
        {
            id: 9,
            image: "https://res.cloudinary.com/dj25aashz/image/upload/v1689472639/e-gadgets/laptop_10_ecdeef.jpg",
            category: "Computers",
            name: "Apple MacBook Pro 16.2 - 32GB - 1TB - 10 Cores - M1 Max - Silver",
            price: "₦ 2,550,000",
            stars: 4,
            reviews: [
                "Sed egestas, ante et vulputate volutpat, eros pede",
                "Semper est, vitae luctus metus libero eu augue. Morbi purus libero, faucibus adipiscing. Sed lectus.",
            ],
        },
        {
            id: 10,
            image: "https://res.cloudinary.com/dj25aashz/image/upload/v1689472639/e-gadgets/laptop_11_uchu27.jpg",
            category: "Computers",
            name: "Hp Stream 11 Intel Celeron 4GB RAM- 64GB HDD ",
            price: "₦ 95,900",
            stars: 2,
            reviews: [
                "Sed egestas, ante et vulputate volutpat, eros pede",
                "Semper est, vitae luctus metus libero eu augue. Morbi purus libero, faucibus adipiscing. Sed lectus.",
            ],
        },
        {
            id: 11,
            image: "https://res.cloudinary.com/dj25aashz/image/upload/v1689472639/e-gadgets/laptop_12_xsih5a.jpg",
            category: "Computers",
            name: "DELL CHROMEBOOK 11, 4GB RAM. 16GB SSD + 32GBFLASH",
            price: "₦ 80,000",
            stars: 4,
            reviews: [
                "Sed egestas, ante et vulputate volutpat, eros pede",
                "Semper est, vitae luctus metus libero eu augue. Morbi purus libero, faucibus adipiscing. Sed lectus.",
            ],
        },
        {
            id: 12,
            image: "https://res.cloudinary.com/dj25aashz/image/upload/v1689472640/e-gadgets/laptop_13_ffj5fb.jpg",
            category: "Computers",
            name: "Lenovo IDEAPAD 14 - 20GB RAM- 1TB HDD - INTEL CORE I3",
            price: "₦ 225,410",
            stars: 5,
            reviews: [
                "Sed egestas, ante et vulputate volutpat, eros pede",
                "Semper est, vitae luctus metus libero eu augue. Morbi purus libero, faucibus adipiscing. Sed lectus.",
            ],
        },
        {
            id: 13,
            image: "https://res.cloudinary.com/dj25aashz/image/upload/v1689472640/e-gadgets/laptop_14_mxnif7.jpg",
            category: "Computers",
            name: "Acer Spin 3 X360 Intel Core I5,8gb,256 SSD,Backlit Keyboard",
            price: "₦ 442,000",
            stars: 1,
            reviews: [
                "Sed egestas, ante et vulputate volutpat, eros pede",
                "Semper est, vitae luctus metus libero eu augue. Morbi purus libero, faucibus adipiscing. Sed lectus.",
            ],
        },
        {
            id: 14,
            image: "https://res.cloudinary.com/dj25aashz/image/upload/v1689472641/e-gadgets/laptop_15_nacqwt.jpg",
            category: "Computers",
            name: "Hp 15 Intel Pentium Silver 8GB RAM 1TB HDD",
            price: "₦ 225,410",
            stars: 2,
            reviews: [
                "Sed egestas, ante et vulputate volutpat, eros pede",
                "Semper est, vitae luctus metus libero eu augue. Morbi purus libero, faucibus adipiscing. Sed lectus.",
            ],
        },
        {
            id: 15,
            image: "https://res.cloudinary.com/dj25aashz/image/upload/v1689472641/e-gadgets/laptop_16_yiuhb7.jpg",
            category: "Computers",
            name: "Lenovo Intel Celeron, 64GB, 4GB Windows 10 11.6",
            price: "₦ 95,500",
            stars: 3,
            reviews: [
                "Sed egestas, ante et vulputate volutpat, eros pede",
                "Semper est, vitae luctus metus libero eu augue. Morbi purus libero, faucibus adipiscing. Sed lectus.",
            ],
        },
        {
            id: 16,
            image: "https://res.cloudinary.com/dj25aashz/image/upload/v1689472642/e-gadgets/laptop_17_toojwr.jpg",
            category: "Computers",
            name: "DELL LATITUDE 5430 12TH GEN, INTEL CORE I5 16GB RAM 512GB SSD",
            price: "₦ 579,000",
            stars: 4,
            reviews: [
                "Sed egestas, ante et vulputate volutpat, eros pede",
                "Semper est, vitae luctus metus libero eu augue. Morbi purus libero, faucibus adipiscing. Sed lectus.",
            ],
        },
        {
            id: 17,
            image: "https://res.cloudinary.com/dj25aashz/image/upload/v1689472641/e-gadgets/laptop_18_ew7v3d.jpg",
            category: "Computers",
            name: "Hp ProBook 11 Inches X360- Intel Celeron 128GB SSD- 4GB RAM",
            price: "₦ 127,000",
            stars: 5,
            reviews: [
                "Sed egestas, ante et vulputate volutpat, eros pede",
                "Semper est, vitae luctus metus libero eu augue. Morbi purus libero, faucibus adipiscing. Sed lectus.",
            ],
        },
        {
            id: 18,
            image: "https://res.cloudinary.com/dj25aashz/image/upload/v1689472642/e-gadgets/laptop_19_hyseuc.jpg",
            category: "Computers",
            name: "Lenovo Ideapad 3 Intel Core I3 15 4GB RAM/ 1TB - FreeDOS ",
            price: "₦ 197,900",
            stars: 3,
            reviews: [
                "Sed egestas, ante et vulputate volutpat, eros pede",
                "Semper est, vitae luctus metus libero eu augue. Morbi purus libero, faucibus adipiscing. Sed lectus.",
            ],
        },
        {
            id: 19,
            image: "https://res.cloudinary.com/dj25aashz/image/upload/v1689472642/e-gadgets/laptop_20_go0jxa.jpg",
            category: "Computers",
            name: "DELL Vostro 15-inch Laptop- Intel Core I3- 16GB RAM/11th GEN/1TB HDD",
            price: "₦ 280,000",
            stars: 5,
            reviews: [
                "Sed egestas, ante et vulputate volutpat, eros pede",
                "Semper est, vitae luctus metus libero eu augue. Morbi purus libero, faucibus adipiscing. Sed lectus.",
            ],
        },
    ],
    phones: [
        {
            id: 0,
            image: "https://res.cloudinary.com/dj25aashz/image/upload/v1689474789/e-gadgets/phone_01_l9czmf.jpg",
            category: "Phones",
            name: "Samsung Galaxy S10 6.1-Inch AMOLED (8GB, 128GB ROM)",
            price: "₦ 153,000",
            stars: 5,
            reviews: [
                "Sed egestas, ante et vulputate volutpat, eros pede",
                "Semper est, vitae luctus metus libero eu augue. Morbi purus libero, faucibus adipiscing. Sed lectus.",
            ],
        },
        {
            id: 1,
            image: "https://res.cloudinary.com/dj25aashz/image/upload/v1689474789/e-gadgets/phone_02_qgirh0.jpg",
            category: "Phones",
            name: "Samsung Galaxy A34 5G 6.4 6GB RAM/128GB ROM",
            price: "₦ 232,750",
            stars: 2,
            reviews: [
                "Sed egestas, ante et vulputate volutpat, eros pede",
                "Semper est, vitae luctus metus libero eu augue. Morbi purus libero, faucibus adipiscing. Sed lectus.",
            ],
        },
        {
            id: 2,
            image: "https://res.cloudinary.com/dj25aashz/image/upload/v1689474789/e-gadgets/phone_03_so2svf.jpg",
            category: "Phones",
            name: "Tecno Spark 10c 6.6 4GB RAM/ 128GB ROM Android 13 - Blue",
            price: "₦ 76,600",
            stars: 4,
            reviews: [
                "Sed egestas, ante et vulputate volutpat, eros pede",
                "Semper est, vitae luctus metus libero eu augue. Morbi purus libero, faucibus adipiscing. Sed lectus.",
            ],
        },
        {
            id: 3,
            image: "https://res.cloudinary.com/dj25aashz/image/upload/v1689474789/e-gadgets/phone_04_fsamgf.jpg",
            category: "Phones",
            name: "Tecno Pop 7 Pro (BF7) 6.6 3GB/64GB",
            price: "₦ 60,690",
            stars: 1,
            reviews: [
                "Sed egestas, ante et vulputate volutpat, eros pede",
                "Semper est, vitae luctus metus libero eu augue. Morbi purus libero, faucibus adipiscing. Sed lectus.",
            ],
        },
        {
            id: 4,
            image: "https://res.cloudinary.com/dj25aashz/image/upload/v1689474789/e-gadgets/phone_05_zksmy6.jpg",
            category: "Phones",
            name: "itel P40 6.6 HD + Waterdrop FullScreen 64GB ROM",
            price: "₦ 56,500",
            stars: 2,
            reviews: [
                "Sed egestas, ante et vulputate volutpat, eros pede",
                "Semper est, vitae luctus metus libero eu augue. Morbi purus libero, faucibus adipiscing. Sed lectus.",
            ],
        },
        {
            id: 5,
            image: "https://res.cloudinary.com/dj25aashz/image/upload/v1689474789/e-gadgets/phone_06_zxjjld.jpg",
            category: "Phones",
            name: "XIAOMI Redmi A2+ 6.52 Inches 2GB RAM 32GB ROM, 5000mAh",
            price: "₦ 47,390",
            stars: 5,
            reviews: [
                "Sed egestas, ante et vulputate volutpat, eros pede",
                "Semper est, vitae luctus metus libero eu augue. Morbi purus libero, faucibus adipiscing. Sed lectus.",
            ],
        },
        {
            id: 6,
            image: "https://res.cloudinary.com/dj25aashz/image/upload/v1689474790/e-gadgets/phone_07_qedwy0.jpg",
            category: "Phones",
            name: ".Samsung Galaxy A14 6.6 4GB RAM/128GB ROM Android 13",
            price: "₦ 110,350",
            stars: 3,
            reviews: [
                "Sed egestas, ante et vulputate volutpat, eros pede",
                "Semper est, vitae luctus metus libero eu augue. Morbi purus libero, faucibus adipiscing. Sed lectus.",
            ],
        },
        {
            id: 7,
            image: "https://res.cloudinary.com/dj25aashz/image/upload/v1689474790/e-gadgets/phone_08_fbor4v.jpg",
            category: "Phones",
            name: "Apple IPHONE 11 PRO MAX 64/4GB (12PM+12PM+12PM) 6.5 3969mAh",
            price: "₦ 415,000",
            stars: 4,
            reviews: [
                "Sed egestas, ante et vulputate volutpat, eros pede",
                "Semper est, vitae luctus metus libero eu augue. Morbi purus libero, faucibus adipiscing. Sed lectus.",
            ],
        },
        {
            id: 8,
            image: "https://res.cloudinary.com/dj25aashz/image/upload/v1689474790/e-gadgets/phone_07_qedwy0.jpg",
            category: "Phones",
            name: "itel A60 6.6 HD+, 2GB RAM + 32GB ROM, 5000mAh Black",
            price: "₦ 45,000",
            stars: 5,
            reviews: [
                "Sed egestas, ante et vulputate volutpat, eros pede",
                "Semper est, vitae luctus metus libero eu augue. Morbi purus libero, faucibus adipiscing. Sed lectus.",
            ],
        },
        {
            id: 9,
            image: "https://res.cloudinary.com/dj25aashz/image/upload/v1689474790/e-gadgets/phone_10_oh5kke.jpg",
            category: "Phones",
            name: "XIAOMI Redmi 12 6.79 8GB RAM/256GB ROM Android 13 - Midnight Black",
            price: "₦ 112,500",
            stars: 4,
            reviews: [
                "Sed egestas, ante et vulputate volutpat, eros pede",
                "Semper est, vitae luctus metus libero eu augue. Morbi purus libero, faucibus adipiscing. Sed lectus.",
            ],
        },
        {
            id: 10,
            image: "https://res.cloudinary.com/dj25aashz/image/upload/v1689474790/e-gadgets/phone_11_tvowiy.jpg",
            category: "Phones",
            name: "Apple Iphone XR 64gb Red, Free Pouch And Screen Protector",
            price: "₦ 240,000",
            stars: 2,
            reviews: [
                "Sed egestas, ante et vulputate volutpat, eros pede",
                "Semper est, vitae luctus metus libero eu augue. Morbi purus libero, faucibus adipiscing. Sed lectus.",
            ],
        },
        {
            id: 11,
            image: "https://res.cloudinary.com/dj25aashz/image/upload/v1689474790/e-gadgets/phone_12_gwvy0o.jpg",
            category: "Phones",
            name: "Tecno Pop 5 Go Bd1 5.71 1GB RAM/16GB ROM Android 10 - Aether Black",
            price: "₦ 40,070",
            stars: 3,
            reviews: [
                "Sed egestas, ante et vulputate volutpat, eros pede",
                "Semper est, vitae luctus metus libero eu augue. Morbi purus libero, faucibus adipiscing. Sed lectus.",
            ],
        },
        {
            id: 12,
            image: "https://res.cloudinary.com/dj25aashz/image/upload/v1689474791/e-gadgets/phone_13_fdffse.jpg",
            category: "Phones",
            name: "itel S23 128GB + 4GB Android 12 BLACK",
            price: "₦ 66,200",
            stars: 4,
            reviews: [
                "Sed egestas, ante et vulputate volutpat, eros pede",
                "Semper est, vitae luctus metus libero eu augue. Morbi purus libero, faucibus adipiscing. Sed lectus.",
            ],
        },
        {
            id: 13,
            image: "https://res.cloudinary.com/dj25aashz/image/upload/v1689474791/e-gadgets/phone_14_uhixls.jpg",
            category: "Phones",
            name: "Tecno Spark 10C (KI5k) 6.6 128GB + Up To 8GB RAM, 16MP, 5000mAh",
            price: "₦ 77,500",
            stars: 3,
            reviews: [
                "Sed egestas, ante et vulputate volutpat, eros pede",
                "Semper est, vitae luctus metus libero eu augue. Morbi purus libero, faucibus adipiscing. Sed lectus.",
            ],
        },
        {
            id: 14,
            image: "https://res.cloudinary.com/dj25aashz/image/upload/v1689474791/e-gadgets/phone_15_rfxolz.jpg",
            category: "Phones",
            name: "Apple IPhone 11 4GB RAM + 128GB ROM - 4G LTE - Single Nano SIM",
            price: "₦ 330,000",
            stars: 4,
            reviews: [
                "Sed egestas, ante et vulputate volutpat, eros pede",
                "Semper est, vitae luctus metus libero eu augue. Morbi purus libero, faucibus adipiscing. Sed lectus.",
            ],
        },
        {
            id: 15,
            image: "https://res.cloudinary.com/dj25aashz/image/upload/v1689474791/e-gadgets/phone_16_qsckk1.jpg",
            category: "Phones",
            name: "Samsung Galaxy Note 9 6.4 (6GB RAM, 128GB ROM)",
            price: "₦ 150,000",
            stars: 5,
            reviews: [
                "Sed egestas, ante et vulputate volutpat, eros pede",
                "Semper est, vitae luctus metus libero eu augue. Morbi purus libero, faucibus adipiscing. Sed lectus.",
            ],
        },
        {
            id: 16,
            image: "https://res.cloudinary.com/dj25aashz/image/upload/v1689474791/e-gadgets/phone_17_i4ylk0.jpg",
            category: "Phones",
            name: "Tecno Phantom X AC8 6.7 FHD 8GB RAM/256GB ROM Android 11",
            price: "₦ 179,999",
            stars: 5,
            reviews: [
                "Sed egestas, ante et vulputate volutpat, eros pede",
                "Semper est, vitae luctus metus libero eu augue. Morbi purus libero, faucibus adipiscing. Sed lectus.",
            ],
        },
        {
            id: 17,
            image: "https://res.cloudinary.com/dj25aashz/image/upload/v1689474791/e-gadgets/phone_18_plpmd9.jpg",
            category: "Phones",
            name: "XIAOMI A1 Plus 6.52 2GB RAM/32GB ROM Android 12 Black",
            price: "₦ 49,000",
            stars: 4,
            reviews: [
                "Sed egestas, ante et vulputate volutpat, eros pede",
                "Semper est, vitae luctus metus libero eu augue. Morbi purus libero, faucibus adipiscing. Sed lectus.",
            ],
        },
        {
            id: 18,
            image: "https://res.cloudinary.com/dj25aashz/image/upload/v1689474792/e-gadgets/phone_19_umke77.jpg",
            category: "Phones",
            name: "Tecno Camon 20 (CK6) 6.67 AMOLED, 256GB ROM + 8GB RAM, 64MP Rear + 32MP Front",
            price: "₦ 145,990",
            stars: 3,
            reviews: [
                "Sed egestas, ante et vulputate volutpat, eros pede",
                "Semper est, vitae luctus metus libero eu augue. Morbi purus libero, faucibus adipiscing. Sed lectus.",
            ],
        },
        {
            id: 19,
            image: "https://res.cloudinary.com/dj25aashz/image/upload/v1689474792/e-gadgets/phone_20_vhdceo.jpg",
            category: "Phones",
            name: "Samsung Galaxy A03 Core 6.5 2GB RAM/ 32GB ROM",
            price: "₦ 54,500",
            stars: 2,
            reviews: [
                "Sed egestas, ante et vulputate volutpat, eros pede",
                "Semper est, vitae luctus metus libero eu augue. Morbi purus libero, faucibus adipiscing. Sed lectus.",
            ],
        },
    ],
    gaming: [
        {
            id: 0,
            image: "https://res.cloudinary.com/dj25aashz/image/upload/v1689477784/e-gadgets/gaming_01_lsoks9.jpg",
            category: "Gaming",
            name: "Sony Ps4 Console 500 GB",
            price: "₦ 144,000",
            stars: 1,
            reviews: [
                "Sed egestas, ante et vulputate volutpat, eros pede",
                "Semper est, vitae luctus metus libero eu augue. Morbi purus libero, faucibus adipiscing. Sed lectus.",
            ],
        },

        {
            id: 1,
            image: "https://res.cloudinary.com/dj25aashz/image/upload/v1689477784/e-gadgets/gaming_02_a763hp.jpg",
            category: "Gaming",
            name: "Sony SLIM PSP CONSOLE WITH 15BONUS GAMES",
            price: "₦ 50,000",
            stars: 3,
            reviews: [
                "Sed egestas, ante et vulputate volutpat, eros pede",
                "Semper est, vitae luctus metus libero eu augue. Morbi purus libero, faucibus adipiscing. Sed lectus.",
            ],
        },

        {
            id: 2,
            image: "https://res.cloudinary.com/dj25aashz/image/upload/v1689477784/e-gadgets/gaming_03_wof9ay.jpg",
            category: "Gaming",
            name: "ANDROID HOLDER+RECIEVER+Wireless Joystick PC Game Controller",
            price: "₦ 14,905",
            stars: 5,
            reviews: [
                "Sed egestas, ante et vulputate volutpat, eros pede",
                "Semper est, vitae luctus metus libero eu augue. Morbi purus libero, faucibus adipiscing. Sed lectus.",
            ],
        },
        {
            id: 3,
            image: "https://res.cloudinary.com/dj25aashz/image/upload/v1689477784/e-gadgets/gaming_04_frwisa.gif",
            category: "Gaming",
            name: "PS4 Controller Pad DualShock4 Official Wireless Gamepad--Dark Blue",
            price: "₦ 10,500",
            stars: 4,
            reviews: [
                "Sed egestas, ante et vulputate volutpat, eros pede",
                "Semper est, vitae luctus metus libero eu augue. Morbi purus libero, faucibus adipiscing. Sed lectus.",
            ],
        },
        {
            id: 4,
            image: "https://res.cloudinary.com/dj25aashz/image/upload/v1689477784/e-gadgets/gaming_05_r5btpr.jpg",
            category: "Gaming",
            name: "Sony PS3 Wireless Pad - Blue And White",
            price: "₦ 9,500",
            stars: 1,
            reviews: [
                "Sed egestas, ante et vulputate volutpat, eros pede",
                "Semper est, vitae luctus metus libero eu augue. Morbi purus libero, faucibus adipiscing. Sed lectus.",
            ],
        },
        {
            id: 5,
            image: "https://res.cloudinary.com/dj25aashz/image/upload/v1689477785/e-gadgets/gaming_06_ucxia0.jpg",
            category: "Gaming",
            name: "EA Sports Fifa 23 Playstation 4",
            price: "₦ 26,800",
            stars: 2,
            reviews: [
                "Sed egestas, ante et vulputate volutpat, eros pede",
                "Semper est, vitae luctus metus libero eu augue. Morbi purus libero, faucibus adipiscing. Sed lectus.",
            ],
        },
        {
            id: 6,
            image: "https://res.cloudinary.com/dj25aashz/image/upload/v1689477786/e-gadgets/gaming_07_sswi5r.jpg",
            category: "Gaming",
            name: "Netherrealm Studios Mortal Kombat 11 Ultimate Ps4",
            price: "₦ 14,175",
            stars: 3,
            reviews: [
                "Sed egestas, ante et vulputate volutpat, eros pede",
                "Semper est, vitae luctus metus libero eu augue. Morbi purus libero, faucibus adipiscing. Sed lectus.",
            ],
        },
        {
            id: 7,
            image: "https://res.cloudinary.com/dj25aashz/image/upload/v1689477785/e-gadgets/gaming_08_b2iu8p.jpg",
            category: "Gaming",
            name: "Sony PS3 Controller Pad - DualShock 3",
            price: "₦ 5,950",
            stars: 4,
            reviews: [
                "Sed egestas, ante et vulputate volutpat, eros pede",
                "Semper est, vitae luctus metus libero eu augue. Morbi purus libero, faucibus adipiscing. Sed lectus.",
            ],
        },
        {
            id: 8,
            image: "https://res.cloudinary.com/dj25aashz/image/upload/v1689477786/e-gadgets/gaming_09_ouia6t.jpg",
            category: "Gaming",
            name: "Sony PS4 Pad (Official Controller) New Dualshock 4",
            price: "₦ 11,999",
            stars: 5,
            reviews: [
                "Sed egestas, ante et vulputate volutpat, eros pede",
                "Semper est, vitae luctus metus libero eu augue. Morbi purus libero, faucibus adipiscing. Sed lectus.",
            ],
        },
        {
            id: 9,
            image: "https://res.cloudinary.com/dj25aashz/image/upload/v1689477786/e-gadgets/gaming_10_mqsgzg.jpg",
            category: "Gaming",
            name: "4pcs Mobile Gaming Thumb Sleeve Sets, Wasp Feelers(2 Pair)",
            price: "₦ 1,399",
            stars: 5,
            reviews: [
                "Sed egestas, ante et vulputate volutpat, eros pede",
                "Semper est, vitae luctus metus libero eu augue. Morbi purus libero, faucibus adipiscing. Sed lectus.",
            ],
        },
        {
            id: 10,
            image: "https://res.cloudinary.com/dj25aashz/image/upload/v1689477786/e-gadgets/gaming_11_t1jo8s.jpg",
            category: "Gaming",
            name: "Sony Call Of Duty: Modern Warfare II - PS 5",
            price: "₦ 43,340",
            stars: 4,
            reviews: [
                "Sed egestas, ante et vulputate volutpat, eros pede",
                "Semper est, vitae luctus metus libero eu augue. Morbi purus libero, faucibus adipiscing. Sed lectus.",
            ],
        },
        {
            id: 11,
            image: "https://res.cloudinary.com/dj25aashz/image/upload/v1689477786/e-gadgets/gaming_12_pevmss.jpg",
            category: "Gaming",
            name: "Nintendo Switch OLED NINTENDO SWITCH (WHITE)",
            price: "₦ 252,340",
            stars: 3,
            reviews: [
                "Sed egestas, ante et vulputate volutpat, eros pede",
                "Semper est, vitae luctus metus libero eu augue. Morbi purus libero, faucibus adipiscing. Sed lectus.",
            ],
        },
        {
            id: 12,
            image: "https://res.cloudinary.com/dj25aashz/image/upload/v1689477786/e-gadgets/gaming_13_hq8xtv.jpg",
            category: "Gaming",
            name: "Xbox 360 Controller Pad USB Wired Gampad Joystick For PC & 360",
            price: "₦ 8,999",
            stars: 2,
            reviews: [
                "Sed egestas, ante et vulputate volutpat, eros pede",
                "Semper est, vitae luctus metus libero eu augue. Morbi purus libero, faucibus adipiscing. Sed lectus.",
            ],
        },
        {
            id: 13,
            image: "https://res.cloudinary.com/dj25aashz/image/upload/v1689477787/e-gadgets/gaming_14_dsfpox.jpg",
            category: "Gaming",
            name: "Official Xbox One Wireless Controller[American Spec]",
            price: "₦ 50,000",
            stars: 1,
            reviews: [
                "Sed egestas, ante et vulputate volutpat, eros pede",
                "Semper est, vitae luctus metus libero eu augue. Morbi purus libero, faucibus adipiscing. Sed lectus.",
            ],
        },
        {
            id: 14,
            image: "https://res.cloudinary.com/dj25aashz/image/upload/v1689477787/e-gadgets/gaming_15_eqnamq.jpg",
            category: "Gaming",
            name: "Sony PS3 Super Slim - 500GB + Extra Controller",
            price: "₦ 97,000",
            stars: 4,
            reviews: [
                "Sed egestas, ante et vulputate volutpat, eros pede",
                "Semper est, vitae luctus metus libero eu augue. Morbi purus libero, faucibus adipiscing. Sed lectus.",
            ],
        },
    ],

    watches: [
        {
            id: 0,
            image: "https://res.cloudinary.com/dj25aashz/image/upload/v1689481145/e-gadgets/watch_01_ixqqdx.jpg",
            category: "Watches",
            name: "Luxury Steel Unisex Bracelet Wristwatch With Date - Black",
            price: "₦ 3,499",
            stars: 1,
            reviews: [
                "Sed egestas, ante et vulputate volutpat, eros pede",
                "Semper est, vitae luctus metus libero eu augue. Morbi purus libero, faucibus adipiscing. Sed lectus.",
            ],
        },
        {
            id: 1,
            image: "https://res.cloudinary.com/dj25aashz/image/upload/v1689481145/e-gadgets/watch_02_xef6bg.jpg",
            category: "Watches",
            name: ".Hi Watch 6 (T500+Pro) Voice Recording Smart - Black",
            price: "₦ 18,705",
            stars: 2,
            reviews: [
                "Sed egestas, ante et vulputate volutpat, eros pede",
                "Semper est, vitae luctus metus libero eu augue. Morbi purus libero, faucibus adipiscing. Sed lectus.",
            ],
        },
        {
            id: 2,
            image: "https://res.cloudinary.com/dj25aashz/image/upload/v1689481145/e-gadgets/watch_03_em5xhx.jpg",
            category: "Watches",
            name: "Luxury Black Full Metal Digital Lava Wrist Watch- Unisex",
            price: "₦ 2,300",
            stars: 4,
            reviews: [
                "Sed egestas, ante et vulputate volutpat, eros pede",
                "Semper est, vitae luctus metus libero eu augue. Morbi purus libero, faucibus adipiscing. Sed lectus.",
            ],
        },
        {
            id: 3,
            image: "https://res.cloudinary.com/dj25aashz/image/upload/v1689481146/e-gadgets/watch_04_jmltc3.jpg",
            category: "Watches",
            name: "2 In 1 Stainless Steel Ladies Women Female Wrist Watch And Bracelet-Blue/Gold",
            price: "₦ 3,999",
            stars: 5,
            reviews: [
                "Sed egestas, ante et vulputate volutpat, eros pede",
                "Semper est, vitae luctus metus libero eu augue. Morbi purus libero, faucibus adipiscing. Sed lectus.",
            ],
        },
        {
            id: 4,
            image: "https://res.cloudinary.com/dj25aashz/image/upload/v1689481145/e-gadgets/watch_05_jb03tc.jpg",
            category: "Watches",
            name: "Skmei Men Watche 5ATM Fashion Casual Digital Wristwatch",
            price: "₦ 5,640",
            stars: 3,
            reviews: [
                "Sed egestas, ante et vulputate volutpat, eros pede",
                "Semper est, vitae luctus metus libero eu augue. Morbi purus libero, faucibus adipiscing. Sed lectus.",
            ],
        },
        {
            id: 5,
            image: "https://res.cloudinary.com/dj25aashz/image/upload/v1689481147/e-gadgets/watch_06_unnx4j.jpg",
            category: "Watches",
            name: "Sports Men Quartz Watches Wrist Watch Gift For Male",
            price: "₦ 2,690",
            stars: 4,
            reviews: [
                "Sed egestas, ante et vulputate volutpat, eros pede",
                "Semper est, vitae luctus metus libero eu augue. Morbi purus libero, faucibus adipiscing. Sed lectus.",
            ],
        },
        {
            id: 6,
            image: "https://res.cloudinary.com/dj25aashz/image/upload/v1689481146/e-gadgets/watch_07_uno6e5.jpg",
            category: "Watches",
            name: "Fngeen Men's Luxury Diamond Waterproof Quartz Watch - Gold",
            price: "₦ 4,300",
            stars: 5,
            reviews: [
                "Sed egestas, ante et vulputate volutpat, eros pede",
                "Semper est, vitae luctus metus libero eu augue. Morbi purus libero, faucibus adipiscing. Sed lectus.",
            ],
        },
        {
            id: 7,
            image: "https://res.cloudinary.com/dj25aashz/image/upload/v1689481147/e-gadgets/watch_08_utipxd.jpg",
            category: "Watches",
            name: "Full Touch Screen Smart Watch - Health Detection",
            price: "₦ 9,643",
            stars: 1,
            reviews: [
                "Sed egestas, ante et vulputate volutpat, eros pede",
                "Semper est, vitae luctus metus libero eu augue. Morbi purus libero, faucibus adipiscing. Sed lectus.",
            ],
        },
        {
            id: 8,
            image: "https://res.cloudinary.com/dj25aashz/image/upload/v1689481147/e-gadgets/watch_09_f30oox.jpg",
            category: "Watches",
            name: "ORUSS Men's Quartz Watch Diamond Waterproof Luminous Calendar Large Steel Strap Watch",
            price: "₦ 2,900",
            stars: 2,
            reviews: [
                "Sed egestas, ante et vulputate volutpat, eros pede",
                "Semper est, vitae luctus metus libero eu augue. Morbi purus libero, faucibus adipiscing. Sed lectus.",
            ],
        },
        {
            id: 9,
            image: "https://res.cloudinary.com/dj25aashz/image/upload/v1689481148/e-gadgets/watch_10_xiywef.jpg",
            category: "Watches",
            name: "Sports Men Quartz Watches Wrist Watch Gift For Male-silver",
            price: "₦ 2,490",
            stars: 3,
            reviews: [
                "Sed egestas, ante et vulputate volutpat, eros pede",
                "Semper est, vitae luctus metus libero eu augue. Morbi purus libero, faucibus adipiscing. Sed lectus.",
            ],
        },
        {
            id: 10,
            image: "https://res.cloudinary.com/dj25aashz/image/upload/v1689481147/e-gadgets/watch_11_rjacit.jpg",
            category: "Watches",
            name: "Geneva Fully Studded Men's Gold-plated Watch",
            price: "₦ 1,590",
            stars: 4,
            reviews: [
                "Sed egestas, ante et vulputate volutpat, eros pede",
                "Semper est, vitae luctus metus libero eu augue. Morbi purus libero, faucibus adipiscing. Sed lectus.",
            ],
        },
        {
            id: 11,
            image: "https://res.cloudinary.com/dj25aashz/image/upload/v1689481146/e-gadgets/watch_12_rmsdhq.jpg",
            category: "Watches",
            name: "Sports Men Quartz Watches Wrist Watch Gift For Male",
            price: "₦ 1,990",
            stars: 5,
            reviews: [
                "Sed egestas, ante et vulputate volutpat, eros pede",
                "Semper est, vitae luctus metus libero eu augue. Morbi purus libero, faucibus adipiscing. Sed lectus.",
            ],
        },
        {
            id: 12,
            image: "https://res.cloudinary.com/dj25aashz/image/upload/v1689481146/e-gadgets/watch_13_mvzbgx.jpg",
            category: "Watches",
            name: "Quartz Watch Ladies Bracelace Watch Women Wrist Watches",
            price: "₦ 3,597",
            stars: 3,
            reviews: [
                "Sed egestas, ante et vulputate volutpat, eros pede",
                "Semper est, vitae luctus metus libero eu augue. Morbi purus libero, faucibus adipiscing. Sed lectus.",
            ],
        },
        {
            id: 13,
            image: "https://res.cloudinary.com/dj25aashz/image/upload/v1689481147/e-gadgets/watch_14_rpd708.jpg",
            category: "Watches",
            name: "2 In 1 Exotic Women Rhinestone Wrist Watch With Bracelet-Gold",
            price: "₦ 3,999",
            stars: 5,
            reviews: [
                "Sed egestas, ante et vulputate volutpat, eros pede",
                "Semper est, vitae luctus metus libero eu augue. Morbi purus libero, faucibus adipiscing. Sed lectus.",
            ],
        },
    ],
};

interface IProducts {
    featured: IProduct[];
    promo_deals: IProductDeals[];
    gift_ideas: IProduct[];
}

export const SpecialProducts: IProducts = {
    featured: [
        {
            id: 0,
            image: "https://res.cloudinary.com/dj25aashz/image/upload/v1689472625/e-gadgets/household_01_naw2ye.jpg",
            category: "Household",
            name: "Hisense 7.5kg Hisense Top Loader Manual Washing Machine (WSQB753)",
            price: "₦ 95,000",
            stars: 3,
            reviews: [
                "Sed egestas, ante et vulputate volutpat, eros pede",
                "Semper est, vitae luctus metus libero eu augue. Morbi purus libero, faucibus adipiscing. Sed lectus.",
            ],
        },

        {
            id: 1,
            image: "https://res.cloudinary.com/dj25aashz/image/upload/v1689472625/e-gadgets/household_02_d764gi.jpg",
            category: "Household",
            name: "7KG 1000W Electric Clothes Dryer Wardrobe Energy Save",
            price: "₦ 55,000",
            stars: 4,
            reviews: [
                "Sed egestas, ante et vulputate volutpat, eros pede",
                "Semper est, vitae luctus metus libero eu augue. Morbi purus libero, faucibus adipiscing. Sed lectus.",
            ],
        },

        {
            id: 2,
            image: "https://res.cloudinary.com/dj25aashz/image/upload/v1689472626/e-gadgets/household_03_hopoyl.jpg",
            category: "Household",
            name: "Nexus 45 Litres Bedside Refrigerator (NX-65) - Silver",
            price: "₦ 58,690",
            stars: 2,
            reviews: [
                "Sed egestas, ante et vulputate volutpat, eros pede",
                "Semper est, vitae luctus metus libero eu augue. Morbi purus libero, faucibus adipiscing. Sed lectus.",
            ],
        },

        {
            id: 3,
            image: "https://res.cloudinary.com/dj25aashz/image/upload/v1689472634/e-gadgets/laptop_01_ijtw4y.jpg",
            category: "Computers",
            name: "Hp Notebook 14 Intel Celeron N4020 8GB RAM 1TB HDD Windows 10 + HP Mouse & USB Light",
            price: "₦ 182,000",
            stars: 4,
            reviews: [
                "Sed egestas, ante et vulputate volutpat, eros pede",
                "Semper est, vitae luctus metus libero eu augue. Morbi purus libero, faucibus adipiscing. Sed lectus.",
            ],
        },
        {
            id: 4,
            image: "https://res.cloudinary.com/dj25aashz/image/upload/v1689472634/e-gadgets/laptop_02_yootb9.jpg",
            category: "Computers",
            name: "Apple MacBook Pro 14 M1 Pro Chip 16GB RAM, 512GB (2021 Model)",
            price: "₦ 1,372,650",
            stars: 2,
            reviews: [
                "Sed egestas, ante et vulputate volutpat, eros pede",
                "Semper est, vitae luctus metus libero eu augue. Morbi purus libero, faucibus adipiscing. Sed lectus.",
            ],
        },
        {
            id: 5,
            image: "https://res.cloudinary.com/dj25aashz/image/upload/v1689472634/e-gadgets/laptop_03_xccyc9.jpg",
            category: "Computers",
            name: "Hp 15 Intel Celeron N4020 8GB RAM/1TB HDD Win 10 +Keyboard",
            price: "₦ 189,500",
            stars: 3,
            reviews: [
                "Sed egestas, ante et vulputate volutpat, eros pede",
                "Semper est, vitae luctus metus libero eu augue. Morbi purus libero, faucibus adipiscing. Sed lectus.",
            ],
        },
        {
            id: 6,
            image: "https://res.cloudinary.com/dj25aashz/image/upload/v1689472638/e-gadgets/laptop_04_ghqbdr.jpg",
            category: "Computers",
            name: "Hp 255 G8 AMD ATHLON 3150U 1TB HDD 8GB 15.6",
            price: "₦ 172,000",
            stars: 4,
            reviews: [
                "Sed egestas, ante et vulputate volutpat, eros pede",
                "Semper est, vitae luctus metus libero eu augue. Morbi purus libero, faucibus adipiscing. Sed lectus.",
            ],
        },
        {
            id: 7,
            image: "https://res.cloudinary.com/dj25aashz/image/upload/v1689481145/e-gadgets/watch_01_ixqqdx.jpg",
            category: "Watches",
            name: "Luxury Steel Unisex Bracelet Wristwatch With Date - Black",
            price: "₦ 3,499",
            stars: 1,
            reviews: [
                "Sed egestas, ante et vulputate volutpat, eros pede",
                "Semper est, vitae luctus metus libero eu augue. Morbi purus libero, faucibus adipiscing. Sed lectus.",
            ],
        },
        {
            id: 8,
            image: "https://res.cloudinary.com/dj25aashz/image/upload/v1689481145/e-gadgets/watch_02_xef6bg.jpg",
            category: "Watches",
            name: ".Hi Watch 6 (T500+Pro) Voice Recording Smart - Black",
            price: "₦ 18,705",
            stars: 2,
            reviews: [
                "Sed egestas, ante et vulputate volutpat, eros pede",
                "Semper est, vitae luctus metus libero eu augue. Morbi purus libero, faucibus adipiscing. Sed lectus.",
            ],
        },
        {
            id: 9,
            image: "https://res.cloudinary.com/dj25aashz/image/upload/v1689481145/e-gadgets/watch_03_em5xhx.jpg",
            category: "Watches",
            name: "Luxury Black Full Metal Digital Lava Wrist Watch- Unisex",
            price: "₦ 2,300",
            stars: 4,
            reviews: [
                "Sed egestas, ante et vulputate volutpat, eros pede",
                "Semper est, vitae luctus metus libero eu augue. Morbi purus libero, faucibus adipiscing. Sed lectus.",
            ],
        },
    ],

    promo_deals: [
        {
            id: 10,
            image: "https://res.cloudinary.com/dj25aashz/image/upload/v1689481147/e-gadgets/watch_11_rjacit.jpg",
            category: "Watches",
            name: "Geneva Fully Studded Men's Gold-plated Watch",
            price: "₦ 1,590",
            old_price: "₦ 2,330",
            stars: 4,
            reviews: [
                "Sed egestas, ante et vulputate volutpat, eros pede",
                "Semper est, vitae luctus metus libero eu augue. Morbi purus libero, faucibus adipiscing. Sed lectus.",
            ],
        },

        {
            id: 13,
            image: "https://res.cloudinary.com/dj25aashz/image/upload/v1689481147/e-gadgets/watch_14_rpd708.jpg",
            category: "Watches",
            name: "2 In 1 Exotic Women Rhinestone Wrist Watch With Bracelet-Gold",
            price: "₦ 3,999",
            old_price: "₦ 5,345",
            stars: 5,
            reviews: [
                "Sed egestas, ante et vulputate volutpat, eros pede",
                "Semper est, vitae luctus metus libero eu augue. Morbi purus libero, faucibus adipiscing. Sed lectus.",
            ],
        },
        {
            id: 9,
            image: "https://res.cloudinary.com/dj25aashz/image/upload/v1689477786/e-gadgets/gaming_10_mqsgzg.jpg",
            category: "Gaming",
            name: "4pcs Mobile Gaming Thumb Sleeve Sets, Wasp Feelers(2 Pair)",
            price: "₦ 1,399",
            old_price: "₦ 2,545",
            stars: 5,
            reviews: [
                "Sed egestas, ante et vulputate volutpat, eros pede",
                "Semper est, vitae luctus metus libero eu augue. Morbi purus libero, faucibus adipiscing. Sed lectus.",
            ],
        },
        {
            id: 11,
            image: "https://res.cloudinary.com/dj25aashz/image/upload/v1689481146/e-gadgets/watch_12_rmsdhq.jpg",
            category: "Watches",
            name: "Sports Men Quartz Watches Wrist Watch Gift For Male",
            price: "₦ 1,990",
            old_price: "₦ 2,500",
            stars: 5,
            reviews: [
                "Sed egestas, ante et vulputate volutpat, eros pede",
                "Semper est, vitae luctus metus libero eu augue. Morbi purus libero, faucibus adipiscing. Sed lectus.",
            ],
        },
        {
            id: 1,
            image: "https://res.cloudinary.com/dj25aashz/image/upload/v1689477786/e-gadgets/gaming_11_t1jo8s.jpg",
            category: "Gaming",
            name: "Sony Call Of Duty: Modern Warfare II - PS 5",
            price: "₦ 43,340",
            old_price: "₦ 49,999",
            stars: 4,
            reviews: [
                "Sed egestas, ante et vulputate volutpat, eros pede",
                "Semper est, vitae luctus metus libero eu augue. Morbi purus libero, faucibus adipiscing. Sed lectus.",
            ],
        },
        {
            id: 3,
            image: "https://res.cloudinary.com/dj25aashz/image/upload/v1689472640/e-gadgets/laptop_14_mxnif7.jpg",
            category: "Computers",
            name: "Acer Spin 3 X360 Intel Core I5,8gb,256 SSD,Backlit Keyboard",
            price: "₦ 442,000",
            old_price: "₦ 540, 000",
            stars: 1,
            reviews: [
                "Sed egestas, ante et vulputate volutpat, eros pede",
                "Semper est, vitae luctus metus libero eu augue. Morbi purus libero, faucibus adipiscing. Sed lectus.",
            ],
        },
        {
            id: 5,
            image: "https://res.cloudinary.com/dj25aashz/image/upload/v1689477786/e-gadgets/gaming_12_pevmss.jpg",
            category: "Gaming",
            name: "Nintendo Switch OLED NINTENDO SWITCH (WHITE)",
            price: "₦ 252,340",
            old_price: "₦ 290,000",
            stars: 3,
            reviews: [
                "Sed egestas, ante et vulputate volutpat, eros pede",
                "Semper est, vitae luctus metus libero eu augue. Morbi purus libero, faucibus adipiscing. Sed lectus.",
            ],
        },
        {
            id: 6,
            image: "https://res.cloudinary.com/dj25aashz/image/upload/v1689481146/e-gadgets/watch_13_mvzbgx.jpg",
            category: "Watches",
            name: "Quartz Watch Ladies Bracelace Watch Women Wrist Watches",
            price: "₦ 3,597",
            old_price: "₦ 4,999",
            stars: 3,
            reviews: [
                "Sed egestas, ante et vulputate volutpat, eros pede",
                "Semper est, vitae luctus metus libero eu augue. Morbi purus libero, faucibus adipiscing. Sed lectus.",
            ],
        },
    ],

    gift_ideas: [
        {
            id: 8,
            image: "https://res.cloudinary.com/dj25aashz/image/upload/v1689474790/e-gadgets/phone_07_qedwy0.jpg",
            category: "Phones",
            name: "itel A60 6.6 HD+, 2GB RAM + 32GB ROM, 5000mAh Black",
            price: "₦ 45,000",
            stars: 5,
            reviews: [
                "Sed egestas, ante et vulputate volutpat, eros pede",
                "Semper est, vitae luctus metus libero eu augue. Morbi purus libero, faucibus adipiscing. Sed lectus.",
            ],
        },
        {
            id: 3,
            image: "https://res.cloudinary.com/dj25aashz/image/upload/v1689481146/e-gadgets/watch_04_jmltc3.jpg",
            category: "Watches",
            name: "2 In 1 Stainless Steel Ladies Women Female Wrist Watch And Bracelet-Blue/Gold",
            price: "₦ 3,999",
            stars: 5,
            reviews: [
                "Sed egestas, ante et vulputate volutpat, eros pede",
                "Semper est, vitae luctus metus libero eu augue. Morbi purus libero, faucibus adipiscing. Sed lectus.",
            ],
        },
        {
            id: 9,
            image: "https://res.cloudinary.com/dj25aashz/image/upload/v1689474790/e-gadgets/phone_10_oh5kke.jpg",
            category: "Phones",
            name: "XIAOMI Redmi 12 6.79 8GB RAM/256GB ROM Android 13 - Midnight Black",
            price: "₦ 112,500",
            stars: 4,
            reviews: [
                "Sed egestas, ante et vulputate volutpat, eros pede",
                "Semper est, vitae luctus metus libero eu augue. Morbi purus libero, faucibus adipiscing. Sed lectus.",
            ],
        },
        {
            id: 2,
            image: "https://res.cloudinary.com/dj25aashz/image/upload/v1689481145/e-gadgets/watch_03_em5xhx.jpg",
            category: "Watches",
            name: "Luxury Black Full Metal Digital Lava Wrist Watch- Unisex",
            price: "₦ 2,300",
            stars: 4,
            reviews: [
                "Sed egestas, ante et vulputate volutpat, eros pede",
                "Semper est, vitae luctus metus libero eu augue. Morbi purus libero, faucibus adipiscing. Sed lectus.",
            ],
        },

        {
            id: 10,
            image: "https://res.cloudinary.com/dj25aashz/image/upload/v1689474790/e-gadgets/phone_11_tvowiy.jpg",
            category: "Phones",
            name: "Apple Iphone XR 64gb Red, Free Pouch And Screen Protector",
            price: "₦ 240,000",
            stars: 2,
            reviews: [
                "Sed egestas, ante et vulputate volutpat, eros pede",
                "Semper est, vitae luctus metus libero eu augue. Morbi purus libero, faucibus adipiscing. Sed lectus.",
            ],
        },
        {
            id: 7,
            image: "https://res.cloudinary.com/dj25aashz/image/upload/v1689472639/e-gadgets/laptop_08_gfvwql.jpg",
            category: "Computers",
            name: "Acer Spin 3 X360 Core I5,8gb,256 SSD,Backlit Keyboard Wins 10",
            price: "₦ 439,950",
            stars: 4,
            reviews: [
                "Sed egestas, ante et vulputate volutpat, eros pede",
                "Semper est, vitae luctus metus libero eu augue. Morbi purus libero, faucibus adipiscing. Sed lectus.",
            ],
        },
    ],
};

interface ITProducts {
    all: IProduct[];
    household: IProduct[];
    computers: IProduct[];
    phones: IProduct[];
    gaming: IProduct[];
    watches: IProduct[];
}

export const TrendingProductsArr: ITProducts = {
    all: [
        {
            id: 2,
            image: "https://res.cloudinary.com/dj25aashz/image/upload/v1689472626/e-gadgets/household_03_hopoyl.jpg",
            category: "Household",
            name: "Nexus 45 Litres Bedside Refrigerator (NX-65) - Silver",
            price: "₦ 58,690",
            stars: 2,
            reviews: [
                "Sed egestas, ante et vulputate volutpat, eros pede",
                "Semper est, vitae luctus metus libero eu augue. Morbi purus libero, faucibus adipiscing. Sed lectus.",
            ],
        },
        {
            id: 5,
            image: "https://res.cloudinary.com/dj25aashz/image/upload/v1689481147/e-gadgets/watch_06_unnx4j.jpg",
            category: "Watches",
            name: "Sports Men Quartz Watches Wrist Watch Gift For Male",
            price: "₦ 2,690",
            stars: 4,
            reviews: [
                "Sed egestas, ante et vulputate volutpat, eros pede",
                "Semper est, vitae luctus metus libero eu augue. Morbi purus libero, faucibus adipiscing. Sed lectus.",
            ],
        },
        {
            id: 17,
            image: "https://res.cloudinary.com/dj25aashz/image/upload/v1689472641/e-gadgets/laptop_18_ew7v3d.jpg",
            category: "Computers",
            name: "Hp ProBook 11 Inches X360- Intel Celeron 128GB SSD- 4GB RAM",
            price: "₦ 127,000",
            stars: 5,
            reviews: [
                "Sed egestas, ante et vulputate volutpat, eros pede",
                "Semper est, vitae luctus metus libero eu augue. Morbi purus libero, faucibus adipiscing. Sed lectus.",
            ],
        },
        {
            id: 11,
            image: "https://res.cloudinary.com/dj25aashz/image/upload/v1689477786/e-gadgets/gaming_12_pevmss.jpg",
            category: "Gaming",
            name: "Nintendo Switch OLED NINTENDO SWITCH (WHITE)",
            price: "₦ 252,340",
            stars: 3,
            reviews: [
                "Sed egestas, ante et vulputate volutpat, eros pede",
                "Semper est, vitae luctus metus libero eu augue. Morbi purus libero, faucibus adipiscing. Sed lectus.",
            ],
        },
        {
            id: 3,
            image: "https://res.cloudinary.com/dj25aashz/image/upload/v1689472626/e-gadgets/household_04_bbrdnm.jpg",
            category: "Household",
            name: "Hisense 1HP Split Copper Inverter Air Conditioner (AS09DK)",
            price: "₦ 197,900",
            stars: 1,
            reviews: [
                "Sed egestas, ante et vulputate volutpat, eros pede",
                "Semper est, vitae luctus metus libero eu augue. Morbi purus libero, faucibus adipiscing. Sed lectus.",
            ],
        },
        {
            id: 18,
            image: "https://res.cloudinary.com/dj25aashz/image/upload/v1689472642/e-gadgets/laptop_19_hyseuc.jpg",
            category: "Computers",
            name: "Lenovo Ideapad 3 Intel Core I3 15 4GB RAM/ 1TB - FreeDOS ",
            price: "₦ 197,900",
            stars: 3,
            reviews: [
                "Sed egestas, ante et vulputate volutpat, eros pede",
                "Semper est, vitae luctus metus libero eu augue. Morbi purus libero, faucibus adipiscing. Sed lectus.",
            ],
        },

        {
            id: 4,
            image: "https://res.cloudinary.com/dj25aashz/image/upload/v1689472626/e-gadgets/household_05_mabscw.jpg",
            category: "Household",
            name: "Midea 10kgTwin Tub Washing Machine",
            price: "₦ 197,90",
            stars: 2,
            reviews: [
                "Sed egestas, ante et vulputate volutpat, eros pede",
                "Semper est, vitae luctus metus libero eu augue. Morbi purus libero, faucibus adipiscing. Sed lectus.",
            ],
        },
        {
            id: 19,
            image: "https://res.cloudinary.com/dj25aashz/image/upload/v1689472642/e-gadgets/laptop_20_go0jxa.jpg",
            category: "Computers",
            name: "DELL Vostro 15-inch Laptop- Intel Core I3- 16GB RAM/11th GEN/1TB HDD",
            price: "₦ 280,000",
            stars: 5,
            reviews: [
                "Sed egestas, ante et vulputate volutpat, eros pede",
                "Semper est, vitae luctus metus libero eu augue. Morbi purus libero, faucibus adipiscing. Sed lectus.",
            ],
        },
        {
            id: 8,
            image: "https://res.cloudinary.com/dj25aashz/image/upload/v1689477786/e-gadgets/gaming_09_ouia6t.jpg",
            category: "Gaming",
            name: "Sony PS4 Pad (Official Controller) New Dualshock 4",
            price: "₦ 11,999",
            stars: 5,
            reviews: [
                "Sed egestas, ante et vulputate volutpat, eros pede",
                "Semper est, vitae luctus metus libero eu augue. Morbi purus libero, faucibus adipiscing. Sed lectus.",
            ],
        },
    ],
    household: [
        {
            id: 2,
            image: "https://res.cloudinary.com/dj25aashz/image/upload/v1689472626/e-gadgets/household_03_hopoyl.jpg",
            category: "Household",
            name: "Nexus 45 Litres Bedside Refrigerator (NX-65) - Silver",
            price: "₦ 58,690",
            stars: 2,
            reviews: [
                "Sed egestas, ante et vulputate volutpat, eros pede",
                "Semper est, vitae luctus metus libero eu augue. Morbi purus libero, faucibus adipiscing. Sed lectus.",
            ],
        },

        {
            id: 3,
            image: "https://res.cloudinary.com/dj25aashz/image/upload/v1689472626/e-gadgets/household_04_bbrdnm.jpg",
            category: "Household",
            name: "Hisense 1HP Split Copper Inverter Air Conditioner (AS09DK)",
            price: "₦ 197,900",
            stars: 1,
            reviews: [
                "Sed egestas, ante et vulputate volutpat, eros pede",
                "Semper est, vitae luctus metus libero eu augue. Morbi purus libero, faucibus adipiscing. Sed lectus.",
            ],
        },
        {
            id: 4,
            image: "https://res.cloudinary.com/dj25aashz/image/upload/v1689472626/e-gadgets/household_05_mabscw.jpg",
            category: "Household",
            name: "Midea 10kgTwin Tub Washing Machine",
            price: "₦ 197,90",
            stars: 2,
            reviews: [
                "Sed egestas, ante et vulputate volutpat, eros pede",
                "Semper est, vitae luctus metus libero eu augue. Morbi purus libero, faucibus adipiscing. Sed lectus.",
            ],
        },
    ],
    computers: [
        {
            id: 17,
            image: "https://res.cloudinary.com/dj25aashz/image/upload/v1689472641/e-gadgets/laptop_18_ew7v3d.jpg",
            category: "Computers",
            name: "Hp ProBook 11 Inches X360- Intel Celeron 128GB SSD- 4GB RAM",
            price: "₦ 127,000",
            stars: 5,
            reviews: [
                "Sed egestas, ante et vulputate volutpat, eros pede",
                "Semper est, vitae luctus metus libero eu augue. Morbi purus libero, faucibus adipiscing. Sed lectus.",
            ],
        },
        {
            id: 18,
            image: "https://res.cloudinary.com/dj25aashz/image/upload/v1689472642/e-gadgets/laptop_19_hyseuc.jpg",
            category: "Computers",
            name: "Lenovo Ideapad 3 Intel Core I3 15 4GB RAM/ 1TB - FreeDOS ",
            price: "₦ 197,900",
            stars: 3,
            reviews: [
                "Sed egestas, ante et vulputate volutpat, eros pede",
                "Semper est, vitae luctus metus libero eu augue. Morbi purus libero, faucibus adipiscing. Sed lectus.",
            ],
        },
        {
            id: 19,
            image: "https://res.cloudinary.com/dj25aashz/image/upload/v1689472642/e-gadgets/laptop_20_go0jxa.jpg",
            category: "Computers",
            name: "DELL Vostro 15-inch Laptop- Intel Core I3- 16GB RAM/11th GEN/1TB HDD",
            price: "₦ 280,000",
            stars: 5,
            reviews: [
                "Sed egestas, ante et vulputate volutpat, eros pede",
                "Semper est, vitae luctus metus libero eu augue. Morbi purus libero, faucibus adipiscing. Sed lectus.",
            ],
        },
    ],
    phones: [
        {
            id: 12,
            image: "https://res.cloudinary.com/dj25aashz/image/upload/v1689474791/e-gadgets/phone_13_fdffse.jpg",
            category: "Phones",
            name: "itel S23 128GB + 4GB Android 12 BLACK",
            price: "₦ 66,200",
            stars: 4,
            reviews: [
                "Sed egestas, ante et vulputate volutpat, eros pede",
                "Semper est, vitae luctus metus libero eu augue. Morbi purus libero, faucibus adipiscing. Sed lectus.",
            ],
        },
        {
            id: 13,
            image: "https://res.cloudinary.com/dj25aashz/image/upload/v1689474791/e-gadgets/phone_14_uhixls.jpg",
            category: "Phones",
            name: "Tecno Spark 10C (KI5k) 6.6 128GB + Up To 8GB RAM, 16MP, 5000mAh",
            price: "₦ 77,500",
            stars: 3,
            reviews: [
                "Sed egestas, ante et vulputate volutpat, eros pede",
                "Semper est, vitae luctus metus libero eu augue. Morbi purus libero, faucibus adipiscing. Sed lectus.",
            ],
        },
        {
            id: 14,
            image: "https://res.cloudinary.com/dj25aashz/image/upload/v1689474791/e-gadgets/phone_15_rfxolz.jpg",
            category: "Phones",
            name: "Apple IPhone 11 4GB RAM + 128GB ROM - 4G LTE - Single Nano SIM",
            price: "₦ 330,000",
            stars: 4,
            reviews: [
                "Sed egestas, ante et vulputate volutpat, eros pede",
                "Semper est, vitae luctus metus libero eu augue. Morbi purus libero, faucibus adipiscing. Sed lectus.",
            ],
        },
        {
            id: 15,
            image: "https://res.cloudinary.com/dj25aashz/image/upload/v1689474791/e-gadgets/phone_16_qsckk1.jpg",
            category: "Phones",
            name: "Samsung Galaxy Note 9 6.4 (6GB RAM, 128GB ROM)",
            price: "₦ 150,000",
            stars: 5,
            reviews: [
                "Sed egestas, ante et vulputate volutpat, eros pede",
                "Semper est, vitae luctus metus libero eu augue. Morbi purus libero, faucibus adipiscing. Sed lectus.",
            ],
        },
        {
            id: 16,
            image: "https://res.cloudinary.com/dj25aashz/image/upload/v1689474791/e-gadgets/phone_17_i4ylk0.jpg",
            category: "Phones",
            name: "Tecno Phantom X AC8 6.7 FHD 8GB RAM/256GB ROM Android 11",
            price: "₦ 179,999",
            stars: 5,
            reviews: [
                "Sed egestas, ante et vulputate volutpat, eros pede",
                "Semper est, vitae luctus metus libero eu augue. Morbi purus libero, faucibus adipiscing. Sed lectus.",
            ],
        },
    ],
    gaming: [
        {
            id: 8,
            image: "https://res.cloudinary.com/dj25aashz/image/upload/v1689477786/e-gadgets/gaming_09_ouia6t.jpg",
            category: "Gaming",
            name: "Sony PS4 Pad (Official Controller) New Dualshock 4",
            price: "₦ 11,999",
            stars: 5,
            reviews: [
                "Sed egestas, ante et vulputate volutpat, eros pede",
                "Semper est, vitae luctus metus libero eu augue. Morbi purus libero, faucibus adipiscing. Sed lectus.",
            ],
        },
        {
            id: 9,
            image: "https://res.cloudinary.com/dj25aashz/image/upload/v1689477786/e-gadgets/gaming_10_mqsgzg.jpg",
            category: "Gaming",
            name: "4pcs Mobile Gaming Thumb Sleeve Sets, Wasp Feelers(2 Pair)",
            price: "₦ 1,399",
            stars: 5,
            reviews: [
                "Sed egestas, ante et vulputate volutpat, eros pede",
                "Semper est, vitae luctus metus libero eu augue. Morbi purus libero, faucibus adipiscing. Sed lectus.",
            ],
        },
        {
            id: 10,
            image: "https://res.cloudinary.com/dj25aashz/image/upload/v1689477786/e-gadgets/gaming_11_t1jo8s.jpg",
            category: "Gaming",
            name: "Sony Call Of Duty: Modern Warfare II - PS 5",
            price: "₦ 43,340",
            stars: 4,
            reviews: [
                "Sed egestas, ante et vulputate volutpat, eros pede",
                "Semper est, vitae luctus metus libero eu augue. Morbi purus libero, faucibus adipiscing. Sed lectus.",
            ],
        },
        {
            id: 11,
            image: "https://res.cloudinary.com/dj25aashz/image/upload/v1689477786/e-gadgets/gaming_12_pevmss.jpg",
            category: "Gaming",
            name: "Nintendo Switch OLED NINTENDO SWITCH (WHITE)",
            price: "₦ 252,340",
            stars: 3,
            reviews: [
                "Sed egestas, ante et vulputate volutpat, eros pede",
                "Semper est, vitae luctus metus libero eu augue. Morbi purus libero, faucibus adipiscing. Sed lectus.",
            ],
        },
    ],
    watches: [
        {
            id: 2,
            image: "https://res.cloudinary.com/dj25aashz/image/upload/v1689481145/e-gadgets/watch_03_em5xhx.jpg",
            category: "Watches",
            name: "Luxury Black Full Metal Digital Lava Wrist Watch- Unisex",
            price: "₦ 2,300",
            stars: 4,
            reviews: [
                "Sed egestas, ante et vulputate volutpat, eros pede",
                "Semper est, vitae luctus metus libero eu augue. Morbi purus libero, faucibus adipiscing. Sed lectus.",
            ],
        },
        {
            id: 3,
            image: "https://res.cloudinary.com/dj25aashz/image/upload/v1689481146/e-gadgets/watch_04_jmltc3.jpg",
            category: "Watches",
            name: "2 In 1 Stainless Steel Ladies Women Female Wrist Watch And Bracelet-Blue/Gold",
            price: "₦ 3,999",
            stars: 5,
            reviews: [
                "Sed egestas, ante et vulputate volutpat, eros pede",
                "Semper est, vitae luctus metus libero eu augue. Morbi purus libero, faucibus adipiscing. Sed lectus.",
            ],
        },
        {
            id: 4,
            image: "https://res.cloudinary.com/dj25aashz/image/upload/v1689481145/e-gadgets/watch_05_jb03tc.jpg",
            category: "Watches",
            name: "Skmei Men Watche 5ATM Fashion Casual Digital Wristwatch",
            price: "₦ 5,640",
            stars: 3,
            reviews: [
                "Sed egestas, ante et vulputate volutpat, eros pede",
                "Semper est, vitae luctus metus libero eu augue. Morbi purus libero, faucibus adipiscing. Sed lectus.",
            ],
        },
        {
            id: 5,
            image: "https://res.cloudinary.com/dj25aashz/image/upload/v1689481147/e-gadgets/watch_06_unnx4j.jpg",
            category: "Watches",
            name: "Sports Men Quartz Watches Wrist Watch Gift For Male",
            price: "₦ 2,690",
            stars: 4,
            reviews: [
                "Sed egestas, ante et vulputate volutpat, eros pede",
                "Semper est, vitae luctus metus libero eu augue. Morbi purus libero, faucibus adipiscing. Sed lectus.",
            ],
        },
    ],
};

export const TopProductsArr: ITProducts = {
    all: [
        {
            id: 13,
            image: "https://res.cloudinary.com/dj25aashz/image/upload/v1689474791/e-gadgets/phone_14_uhixls.jpg",
            category: "Phones",
            name: "Tecno Spark 10C (KI5k) 6.6 128GB + Up To 8GB RAM, 16MP, 5000mAh",
            price: "₦ 77,500",
            stars: 3,
            reviews: [
                "Sed egestas, ante et vulputate volutpat, eros pede",
                "Semper est, vitae luctus metus libero eu augue. Morbi purus libero, faucibus adipiscing. Sed lectus.",
            ],
        },

        {
            id: 15,
            image: "https://res.cloudinary.com/dj25aashz/image/upload/v1689472627/e-gadgets/household_16_ayls6y.jpg",
            category: "Household",
            name: "Wireless Automatic Electric Gallon Bottled Rechargeable Water Pump Dispenser",
            price: "₦ 4,500",
            stars: 2,
            reviews: [
                "Sed egestas, ante et vulputate volutpat, eros pede",
                "Semper est, vitae luctus metus libero eu augue. Morbi purus libero, faucibus adipiscing. Sed lectus.",
            ],
        },
        {
            id: 4,
            image: "https://res.cloudinary.com/dj25aashz/image/upload/v1689472637/e-gadgets/laptop_05_ncqus2.jpg",
            category: "Computers",
            name: "Apple 13.6 MacBook Air (M2, Midnight) 8GB /256gb",
            price: "₦ 950,000",
            stars: 1,
            reviews: [
                "Sed egestas, ante et vulputate volutpat, eros pede",
                "Semper est, vitae luctus metus libero eu augue. Morbi purus libero, faucibus adipiscing. Sed lectus.",
            ],
        },
        {
            id: 9,
            image: "https://res.cloudinary.com/dj25aashz/image/upload/v1689481148/e-gadgets/watch_10_xiywef.jpg",
            category: "Watches",
            name: "Sports Men Quartz Watches Wrist Watch Gift For Male-silver",
            price: "₦ 2,490",
            stars: 3,
            reviews: [
                "Sed egestas, ante et vulputate volutpat, eros pede",
                "Semper est, vitae luctus metus libero eu augue. Morbi purus libero, faucibus adipiscing. Sed lectus.",
            ],
        },
        {
            id: 12,
            image: "https://res.cloudinary.com/dj25aashz/image/upload/v1689474791/e-gadgets/phone_13_fdffse.jpg",
            category: "Phones",
            name: "itel S23 128GB + 4GB Android 12 BLACK",
            price: "₦ 66,200",
            stars: 4,
            reviews: [
                "Sed egestas, ante et vulputate volutpat, eros pede",
                "Semper est, vitae luctus metus libero eu augue. Morbi purus libero, faucibus adipiscing. Sed lectus.",
            ],
        },

        {
            id: 16,
            image: "https://res.cloudinary.com/dj25aashz/image/upload/v1689472628/e-gadgets/household_17_jsflmf.jpg",
            category: "Household",
            name: "Ugasun Electric Slow Juicer With Large Feeder",
            price: "₦ 68,999",
            stars: 5,
            reviews: [
                "Sed egestas, ante et vulputate volutpat, eros pede",
                "Semper est, vitae luctus metus libero eu augue. Morbi purus libero, faucibus adipiscing. Sed lectus.",
            ],
        },
        {
            id: 5,
            image: "https://res.cloudinary.com/dj25aashz/image/upload/v1689472637/e-gadgets/laptop_06_ns2bot.jpg",
            category: "Computers",
            name: "DELL Latitude 3350 Intel Pentium 8GB RAM, 256GB SSD",
            price: "₦ 140,000",
            stars: 2,
            reviews: [
                "Sed egestas, ante et vulputate volutpat, eros pede",
                "Semper est, vitae luctus metus libero eu augue. Morbi purus libero, faucibus adipiscing. Sed lectus.",
            ],
        },
    ],
    household: [
        {
            id: 10,
            image: "https://res.cloudinary.com/dj25aashz/image/upload/v1689472627/e-gadgets/household_11_xjixve.jpg",
            category: "Household",
            name: "Pyramid 22Litres(LARGE) Electric Oven,Baking,Toasting,Grilling",
            price: "₦ 27,700",
            stars: 5,
            reviews: [
                "Sed egestas, ante et vulputate volutpat, eros pede",
                "Semper est, vitae luctus metus libero eu augue. Morbi purus libero, faucibus adipiscing. Sed lectus.",
            ],
        },
        {
            id: 11,
            image: "https://res.cloudinary.com/dj25aashz/image/upload/v1689472627/e-gadgets/household_12_lz87xn.jpg",
            category: "Household",
            name: "Speed Electric Hand Mixer",
            price: "₦ 4,980",
            stars: 2,
            reviews: [
                "Sed egestas, ante et vulputate volutpat, eros pede",
                "Semper est, vitae luctus metus libero eu augue. Morbi purus libero, faucibus adipiscing. Sed lectus.",
            ],
        },
        {
            id: 12,
            image: "https://res.cloudinary.com/dj25aashz/image/upload/v1689472627/e-gadgets/household_13_nq6rma.jpg",
            category: "Household",
            name: "3 In 1 Waffle-Sandwich And Grill Maker",
            price: "₦ 19,699",
            stars: 4,
            reviews: [
                "Sed egestas, ante et vulputate volutpat, eros pede",
                "Semper est, vitae luctus metus libero eu augue. Morbi purus libero, faucibus adipiscing. Sed lectus.",
            ],
        },
        {
            id: 13,
            image: "https://res.cloudinary.com/dj25aashz/image/upload/v1689472597/e-gadgets/household_14_ghjhpm.jpg",
            category: "Household",
            name: "Savanna Juice Extractor - STAINLESS",
            price: "₦ 19,000",
            stars: 4,
            reviews: [
                "Sed egestas, ante et vulputate volutpat, eros pede",
                "Semper est, vitae luctus metus libero eu augue. Morbi purus libero, faucibus adipiscing. Sed lectus.",
            ],
        },
        {
            id: 14,
            image: "https://res.cloudinary.com/dj25aashz/image/upload/v1689472627/e-gadgets/household_15_qhgjmj.jpg",
            category: "Household",
            name: "Ox PLUS 18 Standing Fan",
            price: "₦ 12,790",
            stars: 3,
            reviews: [
                "Sed egestas, ante et vulputate volutpat, eros pede",
                "Semper est, vitae luctus metus libero eu augue. Morbi purus libero, faucibus adipiscing. Sed lectus.",
            ],
        },
        {
            id: 15,
            image: "https://res.cloudinary.com/dj25aashz/image/upload/v1689472627/e-gadgets/household_16_ayls6y.jpg",
            category: "Household",
            name: "Wireless Automatic Electric Gallon Bottled Rechargeable Water Pump Dispenser",
            price: "₦ 4,500",
            stars: 2,
            reviews: [
                "Sed egestas, ante et vulputate volutpat, eros pede",
                "Semper est, vitae luctus metus libero eu augue. Morbi purus libero, faucibus adipiscing. Sed lectus.",
            ],
        },
        {
            id: 16,
            image: "https://res.cloudinary.com/dj25aashz/image/upload/v1689472628/e-gadgets/household_17_jsflmf.jpg",
            category: "Household",
            name: "Ugasun Electric Slow Juicer With Large Feeder",
            price: "₦ 68,999",
            stars: 5,
            reviews: [
                "Sed egestas, ante et vulputate volutpat, eros pede",
                "Semper est, vitae luctus metus libero eu augue. Morbi purus libero, faucibus adipiscing. Sed lectus.",
            ],
        },
    ],
    computers: [
        {
            id: 2,
            image: "https://res.cloudinary.com/dj25aashz/image/upload/v1689472634/e-gadgets/laptop_03_xccyc9.jpg",
            category: "Computers",
            name: "Hp 15 Intel Celeron N4020 8GB RAM/1TB HDD Win 10 +Keyboard",
            price: "₦ 189,500",
            stars: 3,
            reviews: [
                "Sed egestas, ante et vulputate volutpat, eros pede",
                "Semper est, vitae luctus metus libero eu augue. Morbi purus libero, faucibus adipiscing. Sed lectus.",
            ],
        },
        {
            id: 3,
            image: "https://res.cloudinary.com/dj25aashz/image/upload/v1689472638/e-gadgets/laptop_04_ghqbdr.jpg",
            category: "Computers",
            name: "Hp 255 G8 AMD ATHLON 3150U 1TB HDD 8GB 15.6",
            price: "₦ 172,000",
            stars: 4,
            reviews: [
                "Sed egestas, ante et vulputate volutpat, eros pede",
                "Semper est, vitae luctus metus libero eu augue. Morbi purus libero, faucibus adipiscing. Sed lectus.",
            ],
        },
        {
            id: 4,
            image: "https://res.cloudinary.com/dj25aashz/image/upload/v1689472637/e-gadgets/laptop_05_ncqus2.jpg",
            category: "Computers",
            name: "Apple 13.6 MacBook Air (M2, Midnight) 8GB /256gb",
            price: "₦ 950,000",
            stars: 1,
            reviews: [
                "Sed egestas, ante et vulputate volutpat, eros pede",
                "Semper est, vitae luctus metus libero eu augue. Morbi purus libero, faucibus adipiscing. Sed lectus.",
            ],
        },
        {
            id: 5,
            image: "https://res.cloudinary.com/dj25aashz/image/upload/v1689472637/e-gadgets/laptop_06_ns2bot.jpg",
            category: "Computers",
            name: "DELL Latitude 3350 Intel Pentium 8GB RAM, 256GB SSD",
            price: "₦ 140,000",
            stars: 2,
            reviews: [
                "Sed egestas, ante et vulputate volutpat, eros pede",
                "Semper est, vitae luctus metus libero eu augue. Morbi purus libero, faucibus adipiscing. Sed lectus.",
            ],
        },
        {
            id: 6,
            image: "https://res.cloudinary.com/dj25aashz/image/upload/v1689472639/e-gadgets/laptop_07_oa6mh6.jpg",
            category: "Computers",
            name: "Lenovo V15-IGL - Celeron N4020 4GB 256GB - FreeDOS",
            price: "₦ 129,800",
            stars: 3,
            reviews: [
                "Sed egestas, ante et vulputate volutpat, eros pede",
                "Semper est, vitae luctus metus libero eu augue. Morbi purus libero, faucibus adipiscing. Sed lectus.",
            ],
        },
    ],
    phones: [
        {
            id: 9,
            image: "https://res.cloudinary.com/dj25aashz/image/upload/v1689474790/e-gadgets/phone_10_oh5kke.jpg",
            category: "Phones",
            name: "XIAOMI Redmi 12 6.79 8GB RAM/256GB ROM Android 13 - Midnight Black",
            price: "₦ 112,500",
            stars: 4,
            reviews: [
                "Sed egestas, ante et vulputate volutpat, eros pede",
                "Semper est, vitae luctus metus libero eu augue. Morbi purus libero, faucibus adipiscing. Sed lectus.",
            ],
        },
        {
            id: 10,
            image: "https://res.cloudinary.com/dj25aashz/image/upload/v1689474790/e-gadgets/phone_11_tvowiy.jpg",
            category: "Phones",
            name: "Apple Iphone XR 64gb Red, Free Pouch And Screen Protector",
            price: "₦ 240,000",
            stars: 2,
            reviews: [
                "Sed egestas, ante et vulputate volutpat, eros pede",
                "Semper est, vitae luctus metus libero eu augue. Morbi purus libero, faucibus adipiscing. Sed lectus.",
            ],
        },
        {
            id: 11,
            image: "https://res.cloudinary.com/dj25aashz/image/upload/v1689474790/e-gadgets/phone_12_gwvy0o.jpg",
            category: "Phones",
            name: "Tecno Pop 5 Go Bd1 5.71 1GB RAM/16GB ROM Android 10 - Aether Black",
            price: "₦ 40,070",
            stars: 3,
            reviews: [
                "Sed egestas, ante et vulputate volutpat, eros pede",
                "Semper est, vitae luctus metus libero eu augue. Morbi purus libero, faucibus adipiscing. Sed lectus.",
            ],
        },
        {
            id: 12,
            image: "https://res.cloudinary.com/dj25aashz/image/upload/v1689474791/e-gadgets/phone_13_fdffse.jpg",
            category: "Phones",
            name: "itel S23 128GB + 4GB Android 12 BLACK",
            price: "₦ 66,200",
            stars: 4,
            reviews: [
                "Sed egestas, ante et vulputate volutpat, eros pede",
                "Semper est, vitae luctus metus libero eu augue. Morbi purus libero, faucibus adipiscing. Sed lectus.",
            ],
        },
        {
            id: 13,
            image: "https://res.cloudinary.com/dj25aashz/image/upload/v1689474791/e-gadgets/phone_14_uhixls.jpg",
            category: "Phones",
            name: "Tecno Spark 10C (KI5k) 6.6 128GB + Up To 8GB RAM, 16MP, 5000mAh",
            price: "₦ 77,500",
            stars: 3,
            reviews: [
                "Sed egestas, ante et vulputate volutpat, eros pede",
                "Semper est, vitae luctus metus libero eu augue. Morbi purus libero, faucibus adipiscing. Sed lectus.",
            ],
        },
        {
            id: 14,
            image: "https://res.cloudinary.com/dj25aashz/image/upload/v1689474791/e-gadgets/phone_15_rfxolz.jpg",
            category: "Phones",
            name: "Apple IPhone 11 4GB RAM + 128GB ROM - 4G LTE - Single Nano SIM",
            price: "₦ 330,000",
            stars: 4,
            reviews: [
                "Sed egestas, ante et vulputate volutpat, eros pede",
                "Semper est, vitae luctus metus libero eu augue. Morbi purus libero, faucibus adipiscing. Sed lectus.",
            ],
        },
    ],
    gaming: [
        {
            id: 7,
            image: "https://res.cloudinary.com/dj25aashz/image/upload/v1689481147/e-gadgets/watch_08_utipxd.jpg",
            category: "Watches",
            name: "Full Touch Screen Smart Watch - Health Detection",
            price: "₦ 9,643",
            stars: 1,
            reviews: [
                "Sed egestas, ante et vulputate volutpat, eros pede",
                "Semper est, vitae luctus metus libero eu augue. Morbi purus libero, faucibus adipiscing. Sed lectus.",
            ],
        },
        {
            id: 8,
            image: "https://res.cloudinary.com/dj25aashz/image/upload/v1689481147/e-gadgets/watch_09_f30oox.jpg",
            category: "Watches",
            name: "ORUSS Men's Quartz Watch Diamond Waterproof Luminous Calendar Large Steel Strap Watch",
            price: "₦ 2,900",
            stars: 2,
            reviews: [
                "Sed egestas, ante et vulputate volutpat, eros pede",
                "Semper est, vitae luctus metus libero eu augue. Morbi purus libero, faucibus adipiscing. Sed lectus.",
            ],
        },
        {
            id: 9,
            image: "https://res.cloudinary.com/dj25aashz/image/upload/v1689481148/e-gadgets/watch_10_xiywef.jpg",
            category: "Watches",
            name: "Sports Men Quartz Watches Wrist Watch Gift For Male-silver",
            price: "₦ 2,490",
            stars: 3,
            reviews: [
                "Sed egestas, ante et vulputate volutpat, eros pede",
                "Semper est, vitae luctus metus libero eu augue. Morbi purus libero, faucibus adipiscing. Sed lectus.",
            ],
        },
    ],
    watches: [
        {
            id: 4,
            image: "https://res.cloudinary.com/dj25aashz/image/upload/v1689481145/e-gadgets/watch_05_jb03tc.jpg",
            category: "Watches",
            name: "Skmei Men Watche 5ATM Fashion Casual Digital Wristwatch",
            price: "₦ 5,640",
            stars: 3,
            reviews: [
                "Sed egestas, ante et vulputate volutpat, eros pede",
                "Semper est, vitae luctus metus libero eu augue. Morbi purus libero, faucibus adipiscing. Sed lectus.",
            ],
        },
        {
            id: 5,
            image: "https://res.cloudinary.com/dj25aashz/image/upload/v1689481147/e-gadgets/watch_06_unnx4j.jpg",
            category: "Watches",
            name: "Sports Men Quartz Watches Wrist Watch Gift For Male",
            price: "₦ 2,690",
            stars: 4,
            reviews: [
                "Sed egestas, ante et vulputate volutpat, eros pede",
                "Semper est, vitae luctus metus libero eu augue. Morbi purus libero, faucibus adipiscing. Sed lectus.",
            ],
        },
        {
            id: 6,
            image: "https://res.cloudinary.com/dj25aashz/image/upload/v1689481146/e-gadgets/watch_07_uno6e5.jpg",
            category: "Watches",
            name: "Fngeen Men's Luxury Diamond Waterproof Quartz Watch - Gold",
            price: "₦ 4,300",
            stars: 5,
            reviews: [
                "Sed egestas, ante et vulputate volutpat, eros pede",
                "Semper est, vitae luctus metus libero eu augue. Morbi purus libero, faucibus adipiscing. Sed lectus.",
            ],
        },
        {
            id: 7,
            image: "https://res.cloudinary.com/dj25aashz/image/upload/v1689481147/e-gadgets/watch_08_utipxd.jpg",
            category: "Watches",
            name: "Full Touch Screen Smart Watch - Health Detection",
            price: "₦ 9,643",
            stars: 1,
            reviews: [
                "Sed egestas, ante et vulputate volutpat, eros pede",
                "Semper est, vitae luctus metus libero eu augue. Morbi purus libero, faucibus adipiscing. Sed lectus.",
            ],
        },
        {
            id: 8,
            image: "https://res.cloudinary.com/dj25aashz/image/upload/v1689481147/e-gadgets/watch_09_f30oox.jpg",
            category: "Watches",
            name: "ORUSS Men's Quartz Watch Diamond Waterproof Luminous Calendar Large Steel Strap Watch",
            price: "₦ 2,900",
            stars: 2,
            reviews: [
                "Sed egestas, ante et vulputate volutpat, eros pede",
                "Semper est, vitae luctus metus libero eu augue. Morbi purus libero, faucibus adipiscing. Sed lectus.",
            ],
        },
        {
            id: 9,
            image: "https://res.cloudinary.com/dj25aashz/image/upload/v1689481148/e-gadgets/watch_10_xiywef.jpg",
            category: "Watches",
            name: "Sports Men Quartz Watches Wrist Watch Gift For Male-silver",
            price: "₦ 2,490",
            stars: 3,
            reviews: [
                "Sed egestas, ante et vulputate volutpat, eros pede",
                "Semper est, vitae luctus metus libero eu augue. Morbi purus libero, faucibus adipiscing. Sed lectus.",
            ],
        },
    ],
};
